In [1]:
import pandas as pd

data_set = pd.read_csv('data.csv')
print(data_set.head())
age = data_set.iloc[:,1].values
salary=data_set.iloc[:,2].values
print("\n Original age data values :\n", age)
print("\n Original salary data values :\n", salary)


#Binarizing values
from sklearn.preprocessing import Binarizer
x = age
x = x.reshape(1, -1)
y = salary
y = y.reshape(1, -1)

#for age, let threshold be 35, for salary, let threshold be 61000
#age below 35 is binarized to 0
binarizer_1 = Binarizer(35)
#salary below 61000 is binarized to 0
binarizer_2 = Binarizer(61000) 


#Transformed features
print("\n Binarized age : \n",binarizer_1.fit_transform(x))
print("\n Binarized salary : \n",binarizer_2.fit_transform(y))


   Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   27   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40    1000       Yes

 Original age data values :
 [44 27 30 38 40]

 Original salary data values :
 [72000 48000 54000 61000  1000]

 Binarized age : 
 [[1 0 0 1 1]]

 Binarized salary : 
 [[1 0 0 0 0]]


C:\Users\girish\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass threshold=35 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
C:\Users\girish\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass threshold=61000 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
